# Generated by Django 5.0.7 on 2024-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_work_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='previous_work/')),
                ('website', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Previous_work_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='previous_work/')),
                ('website', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Previous_work',
            new_name='Previous_work_1',
        ),
    ]
