# Generated by Django 5.0.7 on 2024-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_previous_work_2_previous_work_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=100)),
                ('description_1', models.TextField()),
                ('picture_1', models.ImageField(upload_to='previous_work/')),
                ('website_1', models.CharField(max_length=500)),
                ('name_2', models.CharField(max_length=100)),
                ('description_2', models.TextField()),
                ('picture_2', models.ImageField(upload_to='previous_work/')),
                ('website_2', models.CharField(max_length=500)),
                ('name_3', models.CharField(max_length=100)),
                ('description_3', models.TextField()),
                ('picture_3', models.ImageField(upload_to='previous_work/')),
                ('website_3', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Previous_work_1',
        ),
        migrations.DeleteModel(
            name='Previous_work_2',
        ),
        migrations.DeleteModel(
            name='Previous_work_3',
        ),
    ]
