# Generated by Django 5.0.7 on 2024-09-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_previous_work_delete_previous_work_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previous_work',
            old_name='description_1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='previous_work',
            old_name='name_1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='previous_work',
            old_name='picture_1',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='previous_work',
            old_name='website_1',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='picture_3',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='website_2',
        ),
        migrations.RemoveField(
            model_name='previous_work',
            name='website_3',
        ),
    ]
