# Generated by Django 5.0.7 on 2024-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_description_1_previous_work_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previous_work',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
